version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
    ports:
      - 33306:3306
    volumes:
      - ./db/tmp:/tmp
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    container_name: sample-db
    entrypoint: >
      sh -c "
        sh /tmp/container-init.sh &&
        docker-entrypoint.sh mysqld \
          --character-set-server=utf8mb4 \
          --collation-server=utf8mb4_unicode_ci
      "
    # command: >
    #   --character-set-server=utf8mb4
    #   --collation-server=utf8mb4_unicode_ci
